networks:
  bridge_network:
    external:
      name: api-pf-planta-pate_bridge_network 

services:
  fastapi_app:
    build: .
    container_name: fastapi_container
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql+pymysql://root:echo3241@172.25.0.6:3306/efa

    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      bridge_network:
        ipv4_address: 172.25.0.3

  nextjs-app:
    build:
      context: ../proyecto-efa
      dockerfile: web.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../proyecto-efa:/app 
    restart: always
    depends_on:
      - fastapi_app
    networks:
      bridge_network:
        ipv4_address: 172.25.0.4

  opc_server:
    build:
      context: ../efa
      dockerfile: server-ua.Dockerfile
    ports:
      - "4840:4840"
    volumes:
      - ../efa:/app 
    restart: always
    depends_on:
      - fastapi_app
    networks:
      bridge_network:
        ipv4_address: 172.25.0.5