INSERT INTO alarma (id, tipoAlarma, descripcion, fechaRegistro) VALUES
(0, 'ESTADO ROBOT', 'Robot buscando Home', NOW()),
(1, 'ESTADO ROBOT', 'Robot buscando gripper', NOW()),
(2, 'ESTADO ROBOT', 'Robot Ingresando a estacion en busca de gripper', NOW()),
(3, 'ESTADO ROBOT', 'Robot saliendo de estacion con nuevo gripper', NOW()),
(4, 'ESTADO ROBOT', 'Robot finalizo la busqueda de nuevo gripper', NOW()),
(5, 'ESTADO ROBOT', 'Robot posicionandose para dejar gripper', NOW()),
(6, 'ESTADO ROBOT', 'Robot ingresando a estacion para dejar gripper', NOW()),
(7, 'ESTADO ROBOT', 'Robot saliendo de estacion sin gripper', NOW()),
(8, 'ESTADO ROBOT', 'Robot finalizo el deja gripper', NOW()),
(9, 'ESTADO ROBOT', 'Robot posicionandose para cambiar gripper', NOW()),
(10, 'ESTADO ROBOT', 'Robot ingresando a estacion para dejar el gripper actual', NOW()),
(11, 'ESTADO ROBOT', 'Robot extrayendo nuevo gripper', NOW()),
(12, 'ESTADO ROBOT', 'Robot saliendo con nuevo gripper', NOW()),
(13, 'ESTADO ROBOT', 'Robot finalizo el cambio de gripper', NOW()),
(14, 'ESTADO ROBOT', 'Robot yendo a posicion de service 1', NOW()),
(15, 'ESTADO ROBOT', 'Robot yendo a posicion de service 2', NOW()),
(16, 'ESTADO ROBOT', 'Robot yendo a posicion de service 3', NOW()),
(17, 'ESTADO ROBOT', 'Robot yendo a posicion de espera', NOW()),
(18, 'ESTADO ROBOT', 'Robot en posicion de espera', NOW()),
(19, 'ESTADO ROBOT', 'Robot entrando a zona de pick', NOW()),
(20, 'ESTADO ROBOT', 'Robot realizando el pickeado de productos', NOW()),
(21, 'ESTADO ROBOT', 'Robot llego a posicion para retiro de zona de SDDA', NOW()),
(22, 'ESTADO ROBOT', 'Robot finalizo el pick de productos y se retiro de zona SDDA', NOW()),
(23, 'ESTADO ROBOT', 'Robot yendo a banda de transporte para dejar los productos', NOW()),
(24, 'ESTADO ROBOT', 'Robot dejo los productos en la banda y se retira', NOW()),
(100, 'ESTADO SDDA', 'Carro de SDDA buscando posicion de HOME', NOW()),
(101, 'ESTADO SDDA', 'Altura de SDDA buscando posicion de HOME', NOW()),
(102, 'ESTADO SDDA', 'SDDA buscando nuevo nivel en velocidad rapida', NOW()),
(103, 'ESTADO SDDA', 'SDDA buscando nivel exacto', NOW()),
(104, 'ESTADO SDDA', 'SDDA nivel detectado', NOW()),
(105, 'ESTADO SDDA', 'SDDA buscando molde en velocidad rapida', NOW()),
(106, 'ESTADO SDDA', 'Carro de SDDA aproximandose a molde', NOW()),
(107, 'ESTADO SDDA', 'SDDA elevando y tomando moldes', NOW()),
(108, 'ESTADO SDDA', 'Carro de SDDA en retroceso', NOW()),
(200, 'FALLA CILINDRO', 'Se detecto que el cilindro de cierre de pinza no llego a la posicion requerida. Revise el cilindro y el sensor desde el modo manual', NOW()),
(201, 'FALLA CILINDRO', 'Se detecto que el cilindro A de elevacion de molde no llego a la posicion requerida. Revise el cilindro y el sensor desde el modo manual', NOW()),
(202, 'FALLA CILINDRO', 'Se detecto que el cilindro B de elevacion de molde no llego a la posicion requerida. Revise el cilindro y el sensor desde el modo manual', NOW()),
(300, 'POSICIONADOR', 'Posicionador no llego a la posicion requerida. Verifique sensores y motor', NOW()),
(301, 'POSICIONADOR', 'Error de seguimiento en el sistema del posicionador. Requiere recalibración', NOW()),
(400, 'GENERALES', 'Falla general del sistema. Verificar condiciones de energía y sensores', NOW()),
(401, 'GENERALES', 'Reinicio inesperado del controlador principal', NOW()),
(500, 'SERVOS', 'Servo de carro fuera de referencia', NOW()),
(501, 'SERVOS', 'Servo de elevación sin respuesta', NOW()),
(600, 'INICIO CICLO', 'Inicio de ciclo automático', NOW()),
(601, 'INICIO CICLO', 'Inicio de ciclo manual', NOW()),
(700, 'CANCELACION', 'Ciclo cancelado por operador', NOW()),
(701, 'CANCELACION', 'Ciclo cancelado por emergencia', NOW()),
(800, 'PULSADORES', 'Pulsador de emergencia activado', NOW()),
(801, 'PULSADORES', 'Pulsador de arranque presionado', NOW());